apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.app.name }}
  labels:
    {{- include "helm.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "helm.selectorLabelsAppServer" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "helm.selectorLabelsAppServer" . | nindent 8 }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.imageApp.repository }}:{{ .Values.imageApp.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.imageApp.pullPolicy }}
          ports:
            - containerPort: 80
          resources:

            {{- toYaml .Values.resources | nindent 12 }}

      imagePullSecrets:
        - name: {{ .Values.imagePullSecret }}