apiVersion: apps/v1
kind: Deployment
metadata:
  name: "{{ include "helm.fullname" . }}-db"
  labels:
    {{- include "helm.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "helm.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "helm.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.imageDb.repository }}:{{ .Values.imageDb.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.imageDb.pullPolicy }}
          ports:
            - containerPort: 1433
          env:
            - name: ACCEPT_EULA
              value: "Y"
            - name: SA_PASSWORD
              value: "P@ssword"
          volumeMounts:
            - name: mssqldir
              mountPath: /var/opt/mssql
          resources:
            {{- toYaml .Values.resources | nindent 12 }}

      volumes:
       - name: mssqldir
         hostPath:
            path: /var/opt/mssql
            type: DirectoryOrCreate

      imagePullSecrets:
        - name: private-docker-registry-cred