apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "helm.fullname" . }}
  annotations:
    kubernetes.io/ingress.class: azure/application-gateway
    cert-manager.io/issuer: {{ .Values.cert.name }}
    cert-manager.io/acme-challenge-type: http01
spec:
  tls:
    - secretName: {{ .Values.ingress.tlsSecret }}
      hosts:
        - {{ .Values.ingress.host }}
  rules:
  - host: {{ .Values.ingress.host }}
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: {{ .Values.app.name }}
            port:
              number: 80