kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: {{ .Values.db.name }}
  annotations:
    volume.beta.kubernetes.io/storage-class: azure-disk
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 4Gi