apiVersion: secrets-store.csi.x-k8s.io/v1alpha1
kind: SecretProviderClass
metadata:
  name: secretstore
spec:
  provider: azure
  secretObjects:
  - secretName: importfile-cred
    type: Opaque
    data: 
    - objectName: importfile-identity-clientsecret
      key: identitykey
    - objectName: importfile-storage-accountkey
      key: storagekey
  - secretName: db-cred
    type: Opaque
    data: 
    - objectName: raspi-app-db-user-password
      key: appuser
    - objectName: raspi-sa-password
      key: sa
  parameters:
    usePodIdentity: "false"                                    
    keyvaultName: "etti-key-vault"
    cloudName: "AzurePublicCloud"                                           
    objects:  |
      array:
        - |
          objectName: importfile-identity-clientsecret
          objectType: secret
          objectVersion: ""
        - |
          objectName: importfile-storage-accountkey
          objectType: secret
          objectVersion: ""
        - |
          objectName: raspi-app-db-user-password
          objectType: secret
          objectVersion: ""
        - |
          objectName: raspi-sa-password
          objectType: secret
          objectVersion: ""
    tenantId: "db9b3aff-8ab6-40b0-a73b-dddc9ca9f31b"