version: '3.4'

services:
  appserver:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:443;http://+:80
    ports:
      - 5001:443
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro
  db:
    ports:
        - '1433:1433'
    environment:
        - ACCEPT_EULA=Y
        - SA_PASSWORD=P@ssword
        - APP_USER_PASSWORD=P3ssword
    volumes:
        - /var/opt/mssql
  importjob:
    environment:
      - STORAGEACCOUNTNAME=raspistorageettenauer
      - STORAGEACCOUNTKEY=Kvcw3iA3s2wTxSuo8BtyDsk0kIh0asVKwwklvZK2JF6XfttiGhU9s6Bdwgo8YJTQ1jzqlrkEr4jlRq1ImoNO4w==
      - IDENTITYCLIENTID=e0acf883-1358-44dc-a964-e1163d8dca78
      - IDENTITYCLIENTSECRET=TTxnt4Uc.8C~0k_Tx_8oX9X0gjLiMYNCRK
      - IDENTITYAUTHORITY=https://login.microsoftonline.com/db9b3aff-8ab6-40b0-a73b-dddc9ca9f31b
      - IMPORTURI=http://appserver/api/Device/NewRecord