version: '3.4'

services:
  raspi.temperature.app.server:
    image: ${DOCKER_REGISTRY-}raspitemperatureappserver
    build:
      context: ../
      dockerfile: source/Server/Dockerfile
    depends_on:
        - db
  db:
    image: ${DOCKER_REGISTRY-}custom-mssql-server-linux
    build:
      context: ../
      dockerfile: mssql/Dockerfile

