apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.importfile.name }}
  labels:
    {{- include "helm.labels" . | nindent 4 }}
type: Opaque
stringData:
  storage_accountkey: <secret>
  identity_clientsecret: <secret>