apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: {{ .Values.importfile.name }}
spec:
  schedule: "*/10 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: {{ .Values.importfile.name }}
            image: "{{ .Values.importfile.repository }}:{{ .Values.importfile.tag | default .Chart.AppVersion }}"
            imagePullPolicy: {{ .Values.importfile.pullPolicy }}
          restartPolicy: OnFailure

          imagePullSecrets:
            - name: {{ .Values.imagePullSecret }}