# Default values for helm.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

imageApp:
  repository: ghcr.io/ettenauer/raspi-blazor-temperature-app
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: "master"

imageDb:
  repository: ghcr.io/ettenauer/raspi-blazor-temperature-app-sqldb
  pullPolicy: Always
  # Overrides the image tag whose default is the chart appVersion.
  tag: "master"

imagePullSecret: "private-docker-registry-cred"
nameOverride: ""
fullnameOverride: ""

service:
  name: web
  type: ClusterIP
  port: 80

ingress:
   host: raspi.local
   path: /app

resources:
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  requests:
   memory: "1Gi"
   cpu: "50m"
  limits:
   memory: "2Gi"
   cpu: "500m"