on:
  push:
    tags:
    - '*'

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}
  PASSWORD: ${{ secrets.GITHUB_TOKEN }}
  USER: ${{ github.actor }}

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Log in to the Container registry
        uses: docker/login-action@v1
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ env.USER }}
          password: ${{env.PASSWORD}}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v3
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}

      - name: Build and push Raspi.Temperature.App.Server
        uses: docker/build-push-action@v2
        with:
          context: ../
          dockerfile: source/Server/Dockerfile
          push: true
          tags: ettenauer/Raspi.Temperature.App:latest

      - name: Build and push Raspi.Temperature.App.SqlDb
        uses: docker/build-push-action@v2
        with:
          context: ../
          dockerfile: mssql/Dockerfile
          push: true
          tags: ettenauer/Raspi.Temperatuzre.SqlDB:latest